/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject2;
import openapitools.model.InlineResponse2004;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "course_id_search", description = "the course_id_search API")
public interface CourseIdSearchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /course_id_search : 查找课程概览
     * 教师/教务可通过此接口获取课程概览
     *
     * @param inlineObject2  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "查找课程概览", nickname = "courseIdSearchGet", notes = "教师/教务可通过此接口获取课程概览", response = InlineResponse2004.class, tags={ "增删改查课程，评教（XW）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse2004.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/course_id_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse2004> courseIdSearchGet(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject2 inlineObject2) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"data\" : [ { \"cou_type\" : \"cou_type\", \"cou_term\" : 0, \"cou_status\" : 6, \"tch_id\" : \"tch_id\", \"tch_name\" : \"tch_name\", \"cou_school\" : \"cou_school\", \"cou_code\" : \"cou_code\", \"cou_name\" : \"cou_name\", \"cou_rank\" : \"cou_rank\" }, { \"cou_type\" : \"cou_type\", \"cou_term\" : 0, \"cou_status\" : 6, \"tch_id\" : \"tch_id\", \"tch_name\" : \"tch_name\", \"cou_school\" : \"cou_school\", \"cou_code\" : \"cou_code\", \"cou_name\" : \"cou_name\", \"cou_rank\" : \"cou_rank\" } ], \"error\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
