/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject3;
import openapitools.model.InlineResponse2005;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "course_search", description = "the course_search API")
public interface CourseSearchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /course_search : 查找课程详情
     * 教师/教务可在对应课程概览下通过此接口查看课程详细信息
     *
     * @param inlineObject3  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "查找课程详情", nickname = "courseSearchGet", notes = "教师/教务可在对应课程概览下通过此接口查看课程详细信息", response = InlineResponse2005.class, tags={ "增删改查课程，评教（XW）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse2005.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/course_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse2005> courseSearchGet(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject3 inlineObject3) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"cou_ifscore\" : \"评分\", \"cou_term\" : -1803530559, \"cou_text\" : \"cou_text\", \"tch_name\" : \"tch_name\", \"cou_school\" : \"cou_school\", \"cou_language\" : \"cou_language\", \"error\" : true, \"cou_score\" : -1517921766, \"cou_type\" : \"公共艺术类\", \"cou_status\" : 441289069, \"tch_id\" : \"tch_id\", \"cou_ifexam\" : \"考查\", \"cou_code\" : \"cou_code\", \"cou_name\" : \"cou_name\", \"cou_rank\" : \"公必\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
