/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineResponse20017;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "course_score", description = "the course_score API")
public interface CourseScoreApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /course_score/specific/{tch_id}/%26{cla_id} : 显示教学班成绩接口
     * 这个接口用来显示一个教学班的成绩（查询）
     *
     * @param tchId  (required)
     * @param claId  (required)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "显示教学班成绩接口", nickname = "courseScoreSpecificTchId26claIdGet", notes = "这个接口用来显示一个教学班的成绩（查询）", response = InlineResponse20017.class, tags={ "教师tch域名内容/教师具体教学班成绩页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20017.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/course_score/specific/{tch_id}/%26{cla_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20017> courseScoreSpecificTchId26claIdGet(@ApiParam(value = "",required=true) @PathVariable("tch_id") String tchId,@ApiParam(value = "",required=true) @PathVariable("cla_id") String claId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"score\" : { \"sco_item_2\" : -1158723813, \"sco_item_3\" : 885365090, \"sco_item_1\" : 273751188, \"sco_cla_id\" : -1517921766, \"sco_score_1\" : 5.962133916683182, \"stu_name\" : \"stu_name\", \"sco_score_2\" : 3.616076749251911, \"sco_note\" : \"sco_note\", \"sco_stu_id\" : 441289069, \"sco_item_4\" : 1847456234 }, \"error\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
