/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject4;
import openapitools.model.InlineResponse2006;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "eva_id_search", description = "the eva_id_search API")
public interface EvaIdSearchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /eva_id_search : 查找评教概览
     * 教师/学生/教务可通过此接口搜索并获取教学班概览（用于评教及查看课程成绩）
     *
     * @param inlineObject4  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "查找评教概览", nickname = "evaIdSearchGet", notes = "教师/学生/教务可通过此接口搜索并获取教学班概览（用于评教及查看课程成绩）", response = InlineResponse2006.class, tags={ "增删改查课程，评教（XW）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse2006.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/eva_id_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse2006> evaIdSearchGet(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject4 inlineObject4) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"data\" : [ { \"cou_ifscore\" : \"评分\", \"cou_term\" : -1803530559, \"cou_text\" : \"cou_text\", \"tch_name\" : \"tch_name\", \"cou_school\" : \"cou_school\", \"cla_toshcool_4\" : \"cla_toshcool_4\", \"cou_language\" : \"cou_language\", \"cla_toschool_2\" : \"cla_toschool_2\", \"cla_weekset\" : \"cla_weekset\", \"cla_id\" : 413233370, \"cla_toschool_1\" : \"cla_toschool_1\", \"cou_score\" : -1517921766, \"cla_toschool_3\" : \"cla_toschool_3\", \"cou_type\" : \"公共艺术类\", \"cou_status\" : 441289069, \"cla_classroom\" : \"cla_classroom\", \"cou_ifexam\" : \"考查\", \"cla_cou_code\" : \"cla_cou_code\", \"cla_tch_id\" : 273751188, \"cla_timeset\" : \"cla_timeset\", \"cou_code\" : \"cou_code\", \"cou_name\" : \"cou_name\", \"cou_rank\" : \"公必\" }, { \"cou_ifscore\" : \"评分\", \"cou_term\" : -1803530559, \"cou_text\" : \"cou_text\", \"tch_name\" : \"tch_name\", \"cou_school\" : \"cou_school\", \"cla_toshcool_4\" : \"cla_toshcool_4\", \"cou_language\" : \"cou_language\", \"cla_toschool_2\" : \"cla_toschool_2\", \"cla_weekset\" : \"cla_weekset\", \"cla_id\" : 413233370, \"cla_toschool_1\" : \"cla_toschool_1\", \"cou_score\" : -1517921766, \"cla_toschool_3\" : \"cla_toschool_3\", \"cou_type\" : \"公共艺术类\", \"cou_status\" : 441289069, \"cla_classroom\" : \"cla_classroom\", \"cou_ifexam\" : \"考查\", \"cla_cou_code\" : \"cla_cou_code\", \"cla_tch_id\" : 273751188, \"cla_timeset\" : \"cla_timeset\", \"cou_code\" : \"cou_code\", \"cou_name\" : \"cou_name\", \"cou_rank\" : \"公必\" } ], \"error\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
