/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject5;
import openapitools.model.InlineResponse2007;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "eva_search", description = "the eva_search API")
public interface EvaSearchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /eva_search : 查找评教详情
     * 在对应教学班概览下通过此接口可查看评教详情
     *
     * @param inlineObject5  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "查找评教详情", nickname = "evaSearchGet", notes = "在对应教学班概览下通过此接口可查看评教详情", response = InlineResponse2007.class, tags={ "增删改查课程，评教（XW）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse2007.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/eva_search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse2007> evaSearchGet(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject5 inlineObject5) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"cou_ifscore\" : \"评分\", \"eva_item_3_avg\" : 5, \"eva_score\" : 7.386281948385884, \"eva_stu_id\" : 435321355, \"error\" : true, \"eva_tch_id\" : 776546569, \"eva_score_avg\" : 0, \"eva_item_2\" : -1707401670, \"eva_text\" : \"null\", \"eva_item_1\" : -1618552611, \"eva_item_4_avg\" : 5, \"cou_status\" : 885365090, \"eva_item_4\" : 793217193, \"eva_item_3\" : -1507784385, \"cou_ifexam\" : \"考查\", \"cou_code\" : \"cou_code\", \"cou_rank\" : \"公必\", \"cou_term\" : -1158723813, \"cou_text\" : \"cou_text\", \"cou_school\" : \"cou_school\", \"eva_cla_id\" : 890262545, \"eva_item_1_avg\" : 6, \"cou_language\" : \"cou_language\", \"cou_score\" : 1847456234, \"cou_type\" : \"公共艺术类\", \"eva_tch_name\" : \"eva_tch_name\", \"eva_item_2_avg\" : 1, \"cou_name\" : \"cou_name\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
