/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject23;
import openapitools.model.InlineResponse20020;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "score{stu_id}", description = "the score{stu_id} API")
public interface ScorestuIdApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /score{stu_id}/%26{cou_term}/%26{cou_rank} : 学生成绩查询页面接口
     * 这个接口用来显示学生的成绩，可选择学期与课程等级来显示（查询）
     *
     * @param stuId  (required)
     * @param couTerm  (required)
     * @param couRank  (required)
     * @param inlineObject23  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "学生成绩查询页面接口", nickname = "scorestuId26couTerm26couRankGet", notes = "这个接口用来显示学生的成绩，可选择学期与课程等级来显示（查询）", response = InlineResponse20020.class, tags={ "学生stu域名内容/学生查询成绩页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20020.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/score{stu_id}/%26{cou_term}/%26{cou_rank}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20020> scorestuId26couTerm26couRankGet(@ApiParam(value = "",required=true) @PathVariable("stu_id") String stuId,@ApiParam(value = "",required=true) @PathVariable("cou_term") String couTerm,@ApiParam(value = "",required=true) @PathVariable("cou_rank") String couRank,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject23 inlineObject23) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"score\" : { \"sco_item_2\" : 885365090, \"sco_item_3\" : 1847456234, \"sco_item_1\" : -1158723813, \"sco_cla_id\" : 413233370, \"tch_name\" : \"tch_name\", \"sco_score_1\" : 5.637376656633329, \"sco_score_2\" : 2.027123023002322, \"sco_note\" : \"sco_note\", \"sco_stu_id\" : -1517921766, \"cou_score\" : 6, \"sco_item_4\" : -594390510 }, \"error\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
