/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.stu;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "api", description = "the api API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/stu_courses/withdraw : 退课
     * 验证学生状态是否正常。 检查学生是否已选该课程，避免退未选的课程。 验证退课是否在允许的时间范围内（例如开学第几周后不能退课）。 从数据库中移除学生的选课信息。 
     *
     * @param body  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "退课", nickname = "apiStuCoursesWithdrawPost", notes = "验证学生状态是否正常。 检查学生是否已选该课程，避免退未选的课程。 验证退课是否在允许的时间范围内（例如开学第几周后不能退课）。 从数据库中移除学生的选课信息。 ", response = Object.class, tags={ "学生stu域名内容/学生选退课（QXY）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Object.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/api/stu_courses/withdraw",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Object> apiStuCoursesWithdrawPost(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) Object body) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
