/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.tch;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "tch", description = "the tch API")
public interface TchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /tch/approvalform : 教师提交审批
     *
     * @param inlineObject22  (optional)
     * @return  (status code 200)
     */
    @ApiOperation(value = "教师提交审批", nickname = "tchApprovalformPost", notes = "", response = Object.class, tags={ "教师tch域名内容/教师提交开课审批", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Object.class) })
    @RequestMapping(value = "/tch/approvalform",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Object> tchApprovalformPost(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject22 inlineObject22) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tch/course_score/{tch_id} : 教师教学班成绩页面
     * 这是一个教师端查看教学班成绩首页的接口，从接口中可以得到教学班id，课程识别码以及和课程名称。
     *
     * @param tchId  (required)
     * @param inlineObject21  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "教师教学班成绩页面", nickname = "tchCourseScoreTchIdGet", notes = "这是一个教师端查看教学班成绩首页的接口，从接口中可以得到教学班id，课程识别码以及和课程名称。", response = InlineResponse20018.class, tags={ "教师tch域名内容/教师具体教学班成绩页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20018.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/tch/course_score/{tch_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20018> tchCourseScoreTchIdGet(@ApiParam(value = "",required=true) @PathVariable("tch_id") String tchId,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject21 inlineObject21) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"teacher\" : { \"cla_cou_code\" : \"cla_cou_code\", \"cou_name\" : \"cou_name\", \"cla_id\" : 6 }, \"error\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tch/grade/show_grade/{tch_id}/%26{cla_id} : 显示分数表接口
     * 这个接口用来显示学生的分数表（查询）
     *
     * @param tchId  (required)
     * @param claId  (required)
     * @param inlineObject19  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "显示分数表接口", nickname = "tchGradeShowGradeTchId26claIdGet", notes = "这个接口用来显示学生的分数表（查询）", response = InlineResponse20016.class, tags={ "教师tch域名内容/教师具体评分页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20016.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/tch/grade/show_grade/{tch_id}/%26{cla_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20016> tchGradeShowGradeTchId26claIdGet(@ApiParam(value = "",required=true) @PathVariable("tch_id") String tchId,@ApiParam(value = "",required=true) @PathVariable("cla_id") String claId,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject19 inlineObject19) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"score\" : { \"sco_item_2\" : -1158723813, \"sco_item_3\" : 885365090, \"sco_item_1\" : 273751188, \"sco_cla_id\" : -1517921766, \"sco_score_1\" : 5.962133916683182, \"stu_name\" : \"stu_name\", \"sco_score_2\" : 3.616076749251911, \"sco_note\" : \"sco_note\", \"sco_stu_id\" : 441289069, \"sco_item_4\" : 1847456234 }, \"error\" : 0.8008281904610115 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tch/grade/{tch_id} : 教师评分页面接口
     * 这是一个教师端评分首页的接口，从接口中可以得到教学班id和课程名称。
     *
     * @param tchId  (required)
     * @param inlineObject18  (optional)
     * @return  (status code 200)
     */
    @ApiOperation(value = "教师评分页面接口", nickname = "tchGradeTchIdGet", notes = "这是一个教师端评分首页的接口，从接口中可以得到教学班id和课程名称。", response = InlineResponse20015.class, tags={ "教师tch域名内容/教师具体评分页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20015.class) })
    @RequestMapping(value = "/tch/grade/{tch_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20015> tchGradeTchIdGet(@ApiParam(value = "",required=true) @PathVariable("tch_id") String tchId,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject18 inlineObject18) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"teacher\" : { \"cou_name\" : \"cou_name\", \"cla_id\" : 6 }, \"error\" : 0.8008281904610115 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /tch/grade/update_grade/{tch_id}/%26{cla_id} : 给学生打分接口
     * 这个接口用来修改学生的成绩（增、改、删）
     *
     * @param tchId  (required)
     * @param claId  (required)
     * @param inlineObject20  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "给学生打分接口", nickname = "tchGradeUpdateGradeTchId26claIdPut", notes = "这个接口用来修改学生的成绩（增、改、删）", response = InlineResponse20017.class, tags={ "教师tch域名内容/教师具体评分页面(KBL)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20017.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/tch/grade/update_grade/{tch_id}/%26{cla_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<InlineResponse20017> tchGradeUpdateGradeTchId26claIdPut(@ApiParam(value = "",required=true) @PathVariable("tch_id") String tchId,@ApiParam(value = "",required=true) @PathVariable("cla_id") String claId,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject20 inlineObject20) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"msg\" : \"msg\", \"score\" : { \"sco_item_2\" : -1158723813, \"sco_item_3\" : 885365090, \"sco_item_1\" : 273751188, \"sco_cla_id\" : -1517921766, \"sco_score_1\" : 5.962133916683182, \"stu_name\" : \"stu_name\", \"sco_score_2\" : 3.616076749251911, \"sco_note\" : \"sco_note\", \"sco_stu_id\" : 441289069, \"sco_item_4\" : 1847456234 }, \"error\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tch/seach_adm : 教师选择审批校级教务员
     *
     * @param rank 教务员等级 (optional)
     * @return  (status code 200)
     */
    @ApiOperation(value = "教师选择审批校级教务员", nickname = "tchSeachAdmGet", notes = "", response = InlineResponse20019.class, tags={ "教师tch域名内容/教师提交开课审批", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20019.class) })
    @RequestMapping(value = "/tch/seach_adm",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20019> tchSeachAdmGet(@ApiParam(value = "教务员等级") @Valid @RequestParam(value = "rank", required = false) Integer rank) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"adm_rank\" : 441289069, \"adm_tel\" : \"adm_tel\", \"adm_id\" : -1803530559, \"adm_name\" : \"adm_name\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
