/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.classtable;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineResponse2008;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;

import java.math.BigDecimal;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "/classtable/getStuTable", description = "the /classtable/getStuTable API")
public interface ClasstableGetStuTableApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET //classtable/getStuTable : 获取学生课表
     *
     * @param stuId  (required)
     * @param claWeekset 周 (required)
     * @param claTimeset 日期 (required)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "获取学生课表", nickname = "classtableGetStuTableGet", notes = "", response = InlineResponse2008.class, tags={ "课表（YJL）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse2008.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "//classtable/getStuTable",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse2008> classtableGetStuTableGet(@ApiParam(value = "", required=true) @RequestPart(value="stu_id", required=true)  String stuId,@ApiParam(value = "周", required=true) @RequestPart(value="cla_weekset", required=true)  BigDecimal claWeekset,@ApiParam(value = "日期", required=true) @RequestPart(value="cla_timeset", required=true)  BigDecimal claTimeset) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cou_ifscore\" : \"评分\", \"cla_toshcool_4\" : \"cla_toshcool_4\", \"cla_toschool_2\" : \"cla_toschool_2\", \"cla_weekset\" : \"cla_weekset\", \"cla_toschool_1\" : \"cla_toschool_1\", \"stu_account\" : \"stu_account\", \"cla_toschool_3\" : \"cla_toschool_3\", \"stu_id\" : -1803530559, \"cou_status\" : 273751188, \"cla_classroom\" : \"cla_classroom\", \"cou_ifexam\" : \"考查\", \"cla_tch_id\" : 1847456234, \"cla_timeset\" : \"cla_timeset\", \"stu_picture\" : \"stu_picture\", \"cou_code\" : \"cou_code\", \"cou_rank\" : \"公必\", \"cou_term\" : 413233370, \"cou_text\" : \"cou_text\", \"stu_sex\" : \"男\", \"cou_school\" : \"cou_school\", \"cou_language\" : \"cou_language\", \"stu_password\" : \"stu_password\", \"stu_tel\" : \"stu_tel\", \"cla_id\" : 885365090, \"cou_score\" : -1158723813, \"stu_grade\" : 441289069, \"cou_type\" : \"公共艺术类\", \"stu_sch\" : \"stu_sch\", \"cla_cou_code\" : \"cla_cou_code\", \"stu_name\" : \"stu_name\", \"stu_status\" : -1517921766, \"cou_name\" : \"cou_name\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
