/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.classtable;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineResponse20011;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;

import java.math.BigDecimal;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "/classtable/getTchTable", description = "the /classtable/getTchTable API")
public interface ClasstableGetTchTableApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET //classtable/getTchTable : 获取老师课表
     *
     * @param tchId  (required)
     * @param claWeekset  (required)
     * @param claTimeset  (required)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "获取老师课表", nickname = "classtableGetTchTableGet", notes = "", response = InlineResponse20011.class, tags={ "课表（YJL）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20011.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "//classtable/getTchTable",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20011> classtableGetTchTableGet(@ApiParam(value = "", required=true) @RequestPart(value="tch_id", required=true)  String tchId,@ApiParam(value = "", required=true) @RequestPart(value="cla_weekset", required=true)  BigDecimal claWeekset,@ApiParam(value = "", required=true) @RequestPart(value="cla_timeset", required=true)  BigDecimal claTimeset) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tch_name\" : \"tch_name\", \"tch_sex\" : \"男\", \"cla_toshcool_4\" : \"cla_toshcool_4\", \"tch_picture\" : \"tch_picture\", \"cla_toschool_2\" : \"cla_toschool_2\", \"cla_weekset\" : \"cla_weekset\", \"cla_id\" : -1517921766, \"cla_toschool_1\" : \"cla_toschool_1\", \"tch_status\" : 441289069, \"cla_toschool_3\" : \"cla_toschool_3\", \"cla_classroom\" : \"cla_classroom\", \"tch_id\" : -1803530559, \"tch_password\" : \"tch_password\", \"cla_cou_code\" : \"cla_cou_code\", \"cla_tch_id\" : 413233370, \"cla_timeset\" : \"cla_timeset\", \"tch_sch\" : \"tch_sch\", \"tch_tel\" : \"tch_tel\", \"tch_account\" : \"tch_account\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
