/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.classtable;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineResponse20010;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;

import java.math.BigDecimal;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-20T21:44:39.267865700+08:00[Asia/Shanghai]")

@Validated
@Api(value = "/classtable/updateStuTable", description = "the /classtable/updateStuTable API")
public interface ClasstableUpdateStuTableApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT //classtable/updateStuTable : 更新学生课表
     *
     * @param stuId  (required)
     * @param claWeekset 周 (required)
     * @param claId  (required)
     * @param startTimeNew 新时间 (required)
     * @param endTimeNew  (required)
     * @param tchId 新老师 (required)
     * @param claClassroom 新地点 (required)
     * @param startTimeOld 旧时间 (required)
     * @param endTimeOld  (required)
     * @param claTimeset 日期 (required)
     * @param claTimesetNew  (required)
     * @param claTchId  (required)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "更新学生课表", nickname = "classtableUpdateStuTablePut", notes = "", response = InlineResponse20010.class, tags={ "课表（YJL）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20010.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "//classtable/updateStuTable",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.PUT)
    default ResponseEntity<InlineResponse20010> classtableUpdateStuTablePut(@ApiParam(value = "", required=true) @RequestPart(value="stu_id", required=true)  String stuId,@ApiParam(value = "周", required=true) @RequestPart(value="cla_weekset", required=true)  BigDecimal claWeekset,@ApiParam(value = "", required=true) @RequestPart(value=" cla_id", required=true)  String claId,@ApiParam(value = "新时间", required=true) @RequestPart(value="start_time_new", required=true)  String startTimeNew,@ApiParam(value = "", required=true) @RequestPart(value="end_time_new", required=true)  String endTimeNew,@ApiParam(value = "新老师", required=true) @RequestPart(value="tch_id", required=true)  String tchId,@ApiParam(value = "新地点", required=true) @RequestPart(value="cla_classroom", required=true)  String claClassroom,@ApiParam(value = "旧时间", required=true) @RequestPart(value="start_time_old", required=true)  String startTimeOld,@ApiParam(value = "", required=true) @RequestPart(value="end_time_old", required=true)  String endTimeOld,@ApiParam(value = "日期", required=true) @RequestPart(value="cla_timeset", required=true)  BigDecimal claTimeset,@ApiParam(value = "", required=true) @RequestPart(value="cla_timeset_new", required=true)  BigDecimal claTimesetNew,@ApiParam(value = "", required=true) @RequestPart(value="cla_tch_id", required=true)  String claTchId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"tch_name\" : \"tch_name\", \"cla_toshcool_4\" : \"cla_toshcool_4\", \"cla_toschool_2\" : \"cla_toschool_2\", \"cla_weekset\" : \"cla_weekset\", \"cla_toschool_1\" : \"cla_toschool_1\", \"stu_account\" : \"stu_account\", \"cla_toschool_3\" : \"cla_toschool_3\", \"stu_id\" : -1803530559, \"cla_classroom\" : \"cla_classroom\", \"tch_id\" : 413233370, \"cla_tch_id\" : 885365090, \"cla_timeset\" : \"cla_timeset\", \"stu_picture\" : \"stu_picture\", \"tch_sch\" : \"tch_sch\", \"tch_tel\" : \"tch_tel\", \"stu_sex\" : \"男\", \"tch_sex\" : \"男\", \"stu_password\" : \"stu_password\", \"stu_tel\" : \"stu_tel\", \"tch_picture\" : \"tch_picture\", \"cla_id\" : -1158723813, \"tch_status\" : 273751188, \"stu_grade\" : 441289069, \"stu_sch\" : \"stu_sch\", \"tch_password\" : \"tch_password\", \"cla_cou_code\" : \"cla_cou_code\", \"stu_name\" : \"stu_name\", \"stu_status\" : -1517921766, \"tch_account\" : \"tch_account\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
