/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apicode.api.adm;

import essusys.coursemanagementsystem.demos.web.controller.ApiUtil;
import io.swagger.annotations.*;
import openapitools.model.InlineObject14;
import openapitools.model.InlineObject17;
import openapitools.model.InlineResponse20012;
import openapitools.model.InlineResponse20014;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import javax.validation.Valid;
import java.util.Optional;

@Validated
@Api(value = "adm", description = "the adm API")
public interface AdmApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /adm/get_activity : 教务员获取活动
     *
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "教务员获取活动", nickname = "admGetActivityGet", notes = "", response = InlineResponse20012.class, tags={ "教务员adm域名内容/教务员增删改查活动（CYN）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20012.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/adm/get_activity",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20012> admGetActivityGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ctrl_name\" : \"ctrl_name\", \"ctrl_number\" : 441289069, \"ctrl_startdate\" : \"2000-01-23T04:56:07.000+00:00\", \"ctrl_enddate\" : \"2000-01-23T04:56:07.000+00:00\", \"ctrl_status\" : -90, \"ctrl_id\" : 171976545, \"ctrl_type\" : 24 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /adm/get_approvalform : 教务员审批界面读取
     *
     * @return  (status code 200)
     */
    @ApiOperation(value = "教务员审批界面读取", nickname = "admGetApprovalformGet", notes = "", response = InlineResponse20014.class, tags={ "教务员adm域名内容/教务员审批", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = InlineResponse20014.class) })
    @RequestMapping(value = "/adm/get_approvalform",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20014> admGetApprovalformGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"apf_status\" : 413233370, \"apf_note\" : \"apf_note\", \"apf_id\" : -1803530559, \"apf_cou_code\" : \"apf_cou_code\", \"apf_tch_id\" : -1517921766, \"apf_adm_id\" : 441289069 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /adm/modify_activity : 教务员修改活动
     *
     * @param inlineObject14  (optional)
     * @return  (status code 200)
     *         or  (status code 404)
     */
    @ApiOperation(value = "教务员修改活动", nickname = "admModifyActivityPut", notes = "", response = Object.class, tags={ "教务员adm域名内容/教务员增删改查活动（CYN）", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Object.class),
        @ApiResponse(code = 404, message = "", response = Object.class) })
    @RequestMapping(value = "/adm/modify_activity",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Object> admModifyActivityPut(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject14 inlineObject14) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /adm/modify_approvalform : 教务员审批
     *
     * @param inlineObject17  (optional)
     * @return  (status code 200)
     */
    @ApiOperation(value = "教务员审批", nickname = "admModifyApprovalformPut", notes = "", response = Object.class, tags={ "教务员adm域名内容/教务员审批", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Object.class) })
    @RequestMapping(value = "/adm/modify_approvalform",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Object> admModifyApprovalformPut(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject17 inlineObject17) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
